import './utils/main-loop';
import './camera/orbit-camera';
import './input/mouse-input';
import './input/touch-input';
import './input/keyboard-input';
import './animation/character-controller';
// import './animation/animator';
import './animation/playbot-animator';
import './animation/playbot-jump';
import './player/player-controller';
import './player/player-input';
// import './player/player-direction';
import './player/player-propulsion';
import './player/movement-direction';
